# permissions for end users to view tinyprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: tinyproject-viewer-role
rules:
- apiGroups:
  - operator.tinysystems.io
  resources:
  - tinyprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.tinysystems.io
  resources:
  - tinyprojects/status
  verbs:
  - get
