apiVersion: operator.tinysystems.io/v1alpha1
kind: TinyWidgetPage
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: tinywidgetpage-sample
spec:
  # TODO(user): Add fields here
